-- Bootcamp Rally Racing Management App 

-- Database
CREATE DATABASE IF NOT EXISTS BOOTCAMP_RALLY;
USE DATABASE BOOTCAMP_RALLY;

-- Schemas
CREATE SCHEMA IF NOT EXISTS CORE;   -- teams, cars
CREATE SCHEMA IF NOT EXISTS OPS;    -- races, results, transactions

-- Teams table: budgets tracked here
CREATE TABLE IF NOT EXISTS CORE.TEAMS (
    TEAM_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TEAM_NAME STRING NOT NULL UNIQUE,
    MEMBERS STRING,
    BUDGET NUMBER(12,2) DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- Cars table: basic performance characteristics
CREATE TABLE IF NOT EXISTS CORE.CARS (
    CAR_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TEAM_ID INTEGER NOT NULL REFERENCES CORE.TEAMS(TEAM_ID),
    CAR_NAME STRING NOT NULL,
    TOP_SPEED_KMH NUMBER(5,1) NOT NULL,              
    ACCELERATION_0_100_S NUMBER(4,2) NOT NULL,       
    HANDLING INT NOT NULL,                           
    RELIABILITY NUMBER(3,2) NOT NULL,                
    WEIGHT_KG INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- Races table: one row per race event
CREATE TABLE IF NOT EXISTS OPS.RACES (
    RACE_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    RACE_NAME STRING NOT NULL,
    DISTANCE_KM NUMBER(6,1) NOT NULL,
    ENTRY_FEE NUMBER(10,2) NOT NULL,
    PRIZE_FIRST NUMBER(10,2) NOT NULL,
    PRIZE_SECOND NUMBER(10,2) NOT NULL,
    PRIZE_THIRD NUMBER(10,2) NOT NULL,
    STARTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- Race results table: each participating car's outcome
CREATE TABLE IF NOT EXISTS OPS.RACE_RESULTS (
    RACE_RESULT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    RACE_ID INTEGER NOT NULL REFERENCES OPS.RACES(RACE_ID),
    CAR_ID INTEGER NOT NULL REFERENCES CORE.CARS(CAR_ID),
    TEAM_ID INTEGER NOT NULL REFERENCES CORE.TEAMS(TEAM_ID),
    FINISH_TIME_MINUTES NUMBER(10,3),
    STATUS STRING NOT NULL,                         
    POSITION INT
);

-- Transactions table: captures budget debits/credits per team
CREATE TABLE IF NOT EXISTS OPS.TRANSACTIONS (
    TRANSACTION_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TEAM_ID INTEGER NOT NULL REFERENCES CORE.TEAMS(TEAM_ID),
    RACE_ID INTEGER,
    AMOUNT NUMBER(12,2) NOT NULL,                 
    CURRENCY STRING DEFAULT 'USD',
    REASON STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);
